// Export all models for easier imports
export { tenants } from './tenants.model';
export { facilities } from './facilities.model';
export { users } from './users.model';
export { patients } from './patients.model';
export { consultations } from './consultations.model';
export { vitals } from './vitals.model';
export { prescriptions } from './prescriptions.model';
export { prescriptionItems } from './prescription-items.model';
export { labRequests } from './lab-requests.model';
export { labResults } from './lab-results.model';
export { inventoryItems } from './inventory-items.model';
export { inventoryBatches } from './inventory-batches.model';
export { dispensations } from './dispensations.model';
export { payments } from './payments.model';
export { documents } from './documents.model';
export { activityLogs } from './activity-logs.model';
export { moduleConfigurations } from './module-configurations.model';
export { moduleCatalog } from './module-catalog.model';
export { modulePackages } from './module-packages.model';
export { tenantSubscriptions } from './tenant-subscriptions.model';
export { appointments } from './appointments.model';
export { testCatalog } from './test-catalog.model';
export { drugCatalog } from './drug-catalog.model';
export { patientAllergies } from './patient-allergies.model';
export { patientConditions } from './patient-conditions.model';
export { notifications } from './notifications.model';
export { prescriptionRefills } from './prescription-refills.model';
export { controlledSubstances } from './controlled-substances.model';
export { qualityControlChecks as qualityControl } from './quality-control.model';
export { labAnalytics } from './lab-analytics.model';
export { modulePermissions } from './module-permissions.model';
export { moduleUsage } from './module-usage.model';
export { sampleTracking } from './sample-tracking.model';
export { equipmentCalibration } from './equipment-calibration.model';
export { resultTemplates } from './result-templates.model';
export { externalLabConfigs } from './external-lab-configs.model';
export { stockMovements } from './stock-movements.model';
export { purchaseOrders } from './purchase-orders.model';
export { roles } from './roles.model';
export { contactSubmissions } from './contact-submissions.model';
export { roomCharges } from './room-charges.model';
export { userSessions } from './user-sessions.model';
export { admissionCharges } from './admission-charges.model';
export { userRoles } from './roles.model';

// Aliases for backward compatibility
export { inventoryItems as inventory } from './inventory-items.model';
export { userRoles as userRoleAssignments } from './roles.model';